### ISSUE TITLE
Conflict with Bracket Pair Colorizer 2

### ISSUE THREAD

**Issue by ImadEM21** [jpruliere/env-autocomplete#9]
Hello !
First of all thank you for this amazing extension it works very well, I've just found a small issue with Bracket Pair Colorizer 2 extension. 
When the env-autocomplete extension is  enabled the Bracket Pair Colorizer 2 extension just stops working and in VS Code it shows that the extension is still enabled.
Not sure if this issue becomes from your extension or if it comes from Pair Colorizer.

**Comment by jpruliere** [comment]
Wow, one year later, here I come 😅 

Like I said in the other issue, some kind of succession is on the way and Max will take ownership of the extension.

Regarding this conflict, recent feedbacks seem to indicate that since bracket pair colorization went native, the extension is not needed anymore and env-autocomplete seems to work fine on its own on latest versions of vsc. I will close this issue for now but don't hesitate to open it again if you feel like it still should be addressed.
